### ISSUE TITLE
local.properties file should not be in the repository

### ISSUE THREAD

**Issue by Gara-Dorta** [ashes999/terrace#6]
As it is advised at the beginning of the file,  the [local.properties](https://github.com/ashes999/terrace/blob/master/template/android-gosuandroid/local.properties) must not be checked into git, otherwise `rake debug` will fail to build the project.

**Comment by ashes999** [comment]
That's a good point. I got my `.gitignore` files mixed up after trying to incorporate libGDX. Thanks for this.

**Comment by ashes999** [comment]
Done.
